/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hbfggswnwvlhibtbzmsq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZmdnc3dud3ZsaGlidGJ6bXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMjAwMjEsImV4cCI6MjA4OTc5NjAyMX0.65LowS1PvFFlviE-hKuUcoXDTLIFQpMryD-zwBx2-VI"