/* AUTOGENERATED FILE — credentials removed from source.
 * Set VITE_SUPABASE_PROJECT_ID and VITE_SUPABASE_ANON_KEY in your .env file.
 * See .env.example for required variables.
 * Never commit a .env file. Never hardcode these values here.
 */

export const projectId: string =
  (import.meta as any).env?.VITE_SUPABASE_PROJECT_ID ?? "";

export const publicAnonKey: string =
  (import.meta as any).env?.VITE_SUPABASE_ANON_KEY ?? "";
