#!/usr/bin/env node
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const OPS = join(ROOT, 'ops')
const QUEUE_FILE = join(OPS, 'BRIDGE_QUEUE.json')
const STATE_FILE = join(OPS, 'BRIDGE_STATE.md')
const NEXT_FILE = join(OPS, 'NEXT_ACTION.md')

const AGENTS = [
  { key: 'claude', branch: 'agent/claude' },
  { key: 'copilot', branch: 'agent/copilot' },
  { key: 'codex', branch: 'agent/codex' },
  { key: 'antigravity', branch: 'agent/antigravity' },
]

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

function readQueue() {
  return JSON.parse(readFileSync(QUEUE_FILE, 'utf8'))
}

function readAgentReport(branch) {
  try {
    const content = git(`show refs/remotes/origin/${branch}:ops/AGENT_REPORT.md`)
    return parseReport(content)
  } catch {
    return null
  }
}

function parseReport(content) {
  const blocks = content.split('BRIDGE_HANDOFF').slice(1)
  if (!blocks.length) return null
  const latest = blocks[0]
  const out = {}
  for (const line of latest.split('\n')) {
    const m = line.match(/^\s+([A-Z_]+):\s+(.+)$/)
    if (m) out[m[1]] = m[2].trim()
  }
  if (!out.TASK_ID) return null
  return {
    taskId: out.TASK_ID,
    pioneer: out.PIONEER || '',
    status: out.STATUS || 'partial',
    summary: out.SUMMARY || '',
    files: out.FILES || '',
    nextMove: out.NEXT_MOVE || '',
    acceptance: out.ACCEPTANCE || 'unmet',
  }
}

function getLastCommitTime(branch) {
  const iso = git(`log refs/remotes/origin/${branch} -1 --format=%cI 2>/dev/null`)
  return iso || null
}

function depsDone(task, statusMap) {
  return (task.depends_on || []).every((id) => statusMap[id]?.done === true)
}

function gateFileName(gate) {
  return `${gate}.md`
}

const queue = readQueue()
const now = new Date().toISOString()
const statusMap = {}
const laneState = {}
const stallReports = []
const emittedGates = []

for (const task of queue.tasks) {
  statusMap[task.id] = { done: false, blocked: false, source: 'queue' }
}

for (const agent of AGENTS) {
  const report = readAgentReport(agent.branch)
  const lastCommit = getLastCommitTime(agent.branch)
  laneState[agent.key] = {
    branch: agent.branch,
    report: report || null,
    lastCommit,
  }

  if (report && statusMap[report.taskId]) {
    statusMap[report.taskId] = {
      done: report.status === 'done' && report.acceptance === 'met',
      blocked: report.status === 'blocked',
      source: agent.key,
      report,
    }
  }

  if (lastCommit) {
    const hours = (Date.now() - new Date(lastCommit).getTime()) / 36e5
    if (hours > 24) {
      const fname = `STALL_REPORT_${agent.key}_${Date.now()}.md`
      const body = `# STALL REPORT — ${agent.key}\n\n- branch: ${agent.branch}\n- last commit: ${lastCommit}\n- stalled hours: ${hours.toFixed(1)}\n- action: verify if lane should remain active or standby\n`
      writeFileSync(join(OPS, fname), body)
      stallReports.push(fname)
    }
  }
}

const eligible = queue.tasks.filter((task) => {
  const state = statusMap[task.id]
  if (state.done) return false
  if (!depsDone(task, statusMap)) return false
  return true
})

const firstByOwner = {}
for (const task of eligible) {
  if (!firstByOwner[task.owner]) firstByOwner[task.owner] = task
}

for (const task of queue.tasks) {
  if (task.gate_on_complete && statusMap[task.id]?.done) {
    const gatePath = join(OPS, gateFileName(task.gate_on_complete))
    if (!existsSync(gatePath)) {
      const body = `# ${task.gate_on_complete}\n\n- emitted: ${now}\n- source task: ${task.id}\n- result: next wave open\n`
      writeFileSync(gatePath, body)
      emittedGates.push(task.gate_on_complete)
    }
  }
}

const activeWave = queue.active_wave
const activeOwnerTask = firstByOwner.claude || eligible[0] || null
const nextText = `# NEXT ACTION — Bridge Output\n\n## Current Wave\n\n${activeWave}\n\n## Eligible Tasks By Owner\n\n${Object.entries(firstByOwner).map(([owner, task]) => `- ${owner}: ${task.id} — ${task.title}`).join('\n') || '- none'}\n\n## Active Owner Lane\n\n${activeOwnerTask ? `- Owner: ${activeOwnerTask.owner}\n- Task: ${activeOwnerTask.id} — ${activeOwnerTask.title}` : '- no eligible task'}\n\n## Rule\n\nDo not skip dependencies.\nDo not open a lower task while a higher eligible task in your lane exists.\n`
writeFileSync(NEXT_FILE, nextText)

const stateDoc = `# BRIDGE STATE — Ruberra\n\n> Generated by the Ruberra Bridge Agent.\n> Updated: ${now}\n\n## Gates Emitted\n\n${emittedGates.length ? emittedGates.map((g) => `- ${g}`).join('\n') : '- none newly emitted'}\n\n## Lane Reports\n\n${AGENTS.map((a) => {
  const lane = laneState[a.key]
  const report = lane.report
  return `### ${a.key}\n- branch: ${a.branch}\n- last commit: ${lane.lastCommit || 'none'}\n- latest task: ${report?.taskId || 'none'}\n- latest status: ${report?.status || 'none'}\n`
}).join('\n')}
\n## Eligible Tasks\n\n${eligible.map((t) => `- ${t.id} — ${t.owner} — ${t.title}`).join('\n') || '- none'}\n\n## Stall Reports\n\n${stallReports.length ? stallReports.map((f) => `- ${f}`).join('\n') : '- none'}\n`
writeFileSync(STATE_FILE, stateDoc)

console.log(`[BRIDGE] updated state. eligible: ${eligible.length}. gates: ${emittedGates.length}. stalls: ${stallReports.length}`)
